### ISSUE TITLE
Fill in Algorithms/Game-Theory table

### ISSUE THREAD

**Issue by RyanFehr** [RyanFehr/HackerRank#12]
For problems without a solution, just Link the title, set difficulty, and set points.

**Comment by dgonz001** [comment]
@RyanFehr for these table issues what README do you want to be filled out, v1 or v2?

**Comment by RyanFehr** [comment]
@dgonz001 I need v1 to  be filled out, I plan on doing all of v2 myself next week at some point

**Comment by dgonz001** [comment]
@RyanFehr I believe that I have added all the problems to the Game Theory listing.

**Comment by RyanFehr** [comment]
Looks good

**Comment by AayushChaturvedi** [comment]
#38 #36 #35 #34 
@RyanFehr I have added all the required inputs like the header, and have updated the readme. Please let me know if any further actions have to be taken.
