### ISSUE TITLE
@rasik210 Update pull requests to follow new README language column formatting

### ISSUE THREAD

**Issue by RyanFehr** [RyanFehr/HackerRank#88]
@rasik210 Please go through your pull requests that are currently open and pull down the most current README and list the problem according to the new format. Sorry for switching the format over without any notice.

**Comment by RyanFehr** [comment]
@rasik210 It is also worth noting that I tend to review your pull requests in order, so to avoid README conflicts on every pull request, you can use the version of the README from your last pull request

**Comment by rasik210** [comment]
Cool. No problem. I got both your points. Let me work it out. I'll notify you on this thread once I've updated all the pull requests with latest changes in readme format.

**Comment by rasik210** [comment]
@RyanFehr I've updated all the currently active pull requests with new format for readme.md file. You should also not face any merging issues if you clear up the pull requests in the order they were created. Please let me know if you face any issue in merging any of the pull requests.
